### ISSUE TITLE
change pictures on landing pages

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-fmw#16]
She wants you to change the images for the landing pages you hand-coded on the other sites. 

Here's the link to the drive folder that has the 3 images she wants you to use: 
https://drive.google.com/folderview?id=0B88_mCI0OTGkRVBSTXdaRXZ2a2M&usp=sharing

due:
11-6-15     12p

**Comment by AaronAguilar** [comment]
Done -- 

http://mindfulnesswalk.org/

http://mindfulnesswalk.com/

**Comment by rodneystrong** [comment]
ty sir
