### ISSUE TITLE
Fix formatting for "Contact" page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-fmw#17]
fresnomindfulnesswalks.org

From client: 
>You see that I added a paragraph about me, but it came out formatted funny, bold, all caps.  I don't like that.  Can you please format the paragraph about me nicely, and then a link about how to sign up for email notifications?  Thanks!  

I trust your judgement on what you think she means by "nicely". 

due:
12-18-15   6p

updated due:
12-20-15  5p

**Comment by rampage1213** [comment]
@rodneystrong I see that this is a WordPress site can you please send me the credentials for this site

**Comment by rodneystrong** [comment]
Crap, sorry about that quintin. Doin that now.

**Comment by rodneystrong** [comment]
creds have been shared. let me know *right away* if they don't work.

**Comment by rampage1213** [comment]
@rodneystrong Shit sorry about getting back to you so late with this but the creds shared with me did not work. I already know how I am going to fix this page up, So when the right creds are shared I will get this done. I'm guessing you will work a little tonight if this is so then I can get this done tonight.

**Comment by rodneystrong** [comment]
dude, it's ok. when I said 'right away' i didn't mean right after i commented. i meant right when you try the creds, if they dont work, then let me know right away. sorry about the confusion and panic. 

i just shared with you another set of creds for FMW so again, please let me know right away if they don't work.

**Comment by rampage1213** [comment]
Those creds worked starting this now

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Good job on this one.. Font is nicely formatted and I like the color choice for emphasis.
